# Generated by Django 3.2.8 on 2021-10-11 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_auto_20211011_1121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AvaliacaoAD',
        ),
    ]
