# Generated by Django 3.2.8 on 2021-10-18 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_delete_avaliacaoad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'verbose_name_plural': 'Cadastro de Pacientes'},
        ),
    ]
