# Generated by Django 3.2.8 on 2021-10-18 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProfissionalEnc', '0002_alter_profissionalenc_options'),
        ('paciente', '0004_alter_paciente_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='Profissional',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='ProfissionalEnc.profissionalenc'),
            preserve_default=False,
        ),
    ]
