# Generated by Django 3.2.8 on 2021-10-18 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfissionalEnc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profissionalenc',
            options={'verbose_name_plural': 'Cadastro de Profissionais'},
        ),
    ]
