# Generated by Django 3.2.8 on 2021-10-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfissionalEnc', '0002_alter_profissionalenc_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissionalenc',
            name='status',
            field=models.CharField(choices=[('A', 'Ativo'), ('N', 'Não Ativo')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
