# Generated by Django 3.2.8 on 2021-10-18 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacaoAD', '0002_alter_avaliacaoad_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaoad',
            name='QOrelha',
            field=models.CharField(choices=[('OE', 'Orelha Esquerda'), ('OD', 'Orelha Direita'), ('AM', 'Ambas')], max_length=2),
        ),
    ]
