# Generated by Django 3.2.8 on 2021-10-25 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ComunicOral', '0002_alter_comunicoral_options'),
        ('avaliacaoAD', '0005_alter_avaliacaoad_qorelha'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComunicOralidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resp_oralidade', models.CharField(choices=[('S', 'Sim'), ('N', 'Nâo')], default='N', max_length=1)),
                ('ComunicOral', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ComunicOral.comunicoral')),
                ('avaliacaoAD', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='avaliacaoAD.avaliacaoad')),
            ],
            options={
                'verbose_name_plural': 'Respostas das Perguntas',
            },
        ),
    ]
