# Generated by Django 3.2.8 on 2021-11-15 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipodevoz', '0001_initial'),
        ('avaliacaoAD', '0006_comunicoralidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoVozCad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repostas', models.CharField(choices=[('S', 'Sim'), ('N', 'Nâo')], default='N', max_length=1)),
                ('avaliacaoAD', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='avaliacaoAD.avaliacaoad')),
                ('tipovoz', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tipodevoz.tipovoz')),
            ],
            options={
                'verbose_name_plural': 'Repostas da Pergunta Tipo Voz',
            },
        ),
    ]
