# Generated by Django 3.2.8 on 2021-11-17 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ressonancia', '0002_alter_ressonancia_options'),
        ('avaliacaoAD', '0007_tipovozcad'),
    ]

    operations = [
        migrations.CreateModel(
            name='RessonanciaCad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(choices=[('S', 'Sim'), ('N', 'Nâo')], default='N', max_length=1)),
                ('avaliacaoAD', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='avaliacaoAD.avaliacaoad')),
                ('ressonancia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ressonancia.ressonancia')),
            ],
            options={
                'verbose_name_plural': 'Repostas das Perguntas Ressonancia',
            },
        ),
    ]
