# Generated by Django 3.2.8 on 2021-11-17 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loudness', '0001_initial'),
        ('pitch', '0001_initial'),
        ('avaliacaoAD', '0009_ataquevocalcad'),
    ]

    operations = [
        migrations.CreateModel(
            name='PitchCad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(choices=[('S', 'Sim'), ('N', 'Nâo')], default='N', max_length=1)),
                ('avaliacaoAD', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='avaliacaoAD.avaliacaoad')),
                ('pitch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pitch.pitch')),
            ],
        ),
        migrations.CreateModel(
            name='Loudness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(choices=[('S', 'Sim'), ('N', 'Nâo')], default='N', max_length=1)),
                ('avaliacaoAD', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='avaliacaoAD.avaliacaoad')),
                ('loudness', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loudness.loudness')),
            ],
        ),
    ]
