# Generated by Django 3.2.8 on 2021-11-18 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loudness', '0001_initial'),
        ('avaliacaoAD', '0010_loudness_pitchcad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Loudness',
            new_name='LoudnessCad',
        ),
    ]
