# Generated by Django 3.2.8 on 2021-11-19 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulacao', '0001_initial'),
        ('qualidadeemis', '0001_initial'),
        ('avaliacaoAD', '0011_rename_loudness_loudnesscad'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualidadeemisCad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(choices=[('S', 'Sim'), ('N', 'Nâo')], default='N', max_length=1)),
                ('avaliacaoAD', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='avaliacaoAD.avaliacaoad')),
                ('qualidadeemis', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='qualidadeemis.qualidadeemis')),
            ],
        ),
        migrations.CreateModel(
            name='ModulacaoCad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(choices=[('S', 'Sim'), ('N', 'Nâo')], default='N', max_length=1)),
                ('avaliacaoAD', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='avaliacaoAD.avaliacaoad')),
                ('modulacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='modulacao.modulacao')),
            ],
        ),
    ]
